version: '3.9'
services:
  mainpage:
    build:
      context: .
      dockerfile: MainPage/Dockerfile
    expose:
      - 5005
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_SA_PASSWORD=${DB_SA_PASSWORD}
      - ConnectionStrings__MainPageDatabase=${DB_CONNECTION_STRING}
    restart: unless-stopped
    networks:
        - nginx-network
        - db-network
  db:
    container_name: ${DB_HOST}
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: ${DB_USER}
    volumes:
      - ./db/data:/var/opt/mssql/data
      - ./db/log:/var/opt/mssql/log
    ports:
    - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=${SA_PASSWORD}
    networks:
        - db-network
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=${HOST_NAME:?error}
    restart: unless-stopped
    depends_on:
      - mainpage
    networks:
      - nginx-network
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
networks:
  nginx-network:
    driver: bridge
  db-network:
    driver: bridge  