version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=${HOST_NAME:?error}
      - BLAZOR_PORT=${BLAZOR_PORT:?error}
    restart: unless-stopped
    depends_on:
      - api
      - blazor
    networks:
      - nginx-network
  api:
    build:
      context: './api/WebApi'
      dockerfile: Dockerfile
    expose:
      - 5000
    restart: unless-stopped
    networks:
      - nginx-network
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
  blazor:
    build:
      context: './BlazorApp/MainPage'
      dockerfile: Dockerfile
    expose:
      - ${BLAZOR_PORT:?error}
    restart: unless-stopped
    environment:
      - BLAZOR_PORT=${BLAZOR_PORT:?error}
    networks:
    - nginx-network
networks:
  nginx-network:
    driver: bridge
