version: '3.9'
services:
  mainpage:
    build:
      context: .
      dockerfile: MainPage/Dockerfile
    expose:
      - 5005
    restart: unless-stopped
    networks:
        - nginx-network
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=${HOST_NAME:?error}
    restart: unless-stopped
    depends_on:
      - mainpage
    networks:
      - nginx-network
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
networks:
  nginx-network:
    driver: bridge
