version: '3.9'
services:
  mainpage:
    build:
      context: .
      dockerfile: MainPage/Dockerfile
    expose:
      - 5005
    depends_on:
      - db
    environment:
      - ConnectionStrings__MainPageDatabase=${DB_CONNECTION_STRING}
    restart: unless-stopped
    networks:
        - nginx-network
        - db-network
  db:
    container_name: ${DB_HOST}
    image: postgres:16.2-alpine
    volumes:
        - ./db/data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
        - db-network
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=${HOST_NAME:?error}
    restart: unless-stopped
    depends_on:
      - mainpage
    networks:
      - nginx-network
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
networks:
  nginx-network:
    driver: bridge
  db-network:
    driver: bridge  