version: '3.9'
services:
  mainpage:
    build:
      context: .
      dockerfile: MainPage/Dockerfile
    expose:
      - 5005
    depends_on:
      - db
    # environment:
    #   - DB_HOST=
    #   - DB_NAME=
    #   - DB_SA_PASSWORD=
    restart: unless-stopped
    networks:
        - nginx-network
        - db-network
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - 1433:1433
    environment:
    - ACCEPT_EULA=Y
    # - SA_PASSWORD=
    networks:
        - db-network
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_HOST=${HOST_NAME:?error}
    restart: unless-stopped
    depends_on:
      - mainpage
    networks:
      - nginx-network
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
networks:
  nginx-network:
    driver: bridge
  db-network:
    driver: bridge  